spring.application.name=l10-02

spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=test_schema
spring.datasource.username=alexionescu
spring.datasource.password=

spring.jpa.show-sql=true