spring.application.name=l09

# only on update
#spring.jpa.hibernate.ddl-auto=update

# will always create (drop + create)
spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=test_schema
spring.datasource.username=alexionescu
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true